server:
  port: 9999

spring:
  devtools:
    livereload:
      enabled: true

  data:
    rest:
      basePath: /api

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:~/test
    username: sa
    password:

#  freemarker:
#    cache: false

#System.setProperty("spring:devtools:restart:enabled", "false");
#System.setProperty("spring:devtools:livereload:enabled", "true");


#redis:
#  server:
---
spring:
  profiles: default
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
  jpa:
    database: h2
    hibernate:
      ddl-auto: update
#      use-new-id-generator-mappings: false
    show-sql: true

