server:
  port: 9999

spring:
  devtools:
    livereload:
      enabled: true

  data:
    rest:
      basePath: /api

#  freemarker:
#    cache: false

#System.setProperty("spring:devtools:restart:enabled", "false");
#System.setProperty("spring:devtools:livereload:enabled", "true");


#redis:
#  server: